[settings]
name = "Dash"
agent_id = "dash/bot"
hivemind = false

root_dir = ""
loadout_file = "loadout.toml"

run_command = ""
run_command_linux = "./run.sh"

[details]
description = "Single-policy RL bot trained with GigaLearn on RocketSim."
fun_fact = "Fun fact pending..."
developer = "wardn"
language = "C++"
tags = ["1v1"] # TODO "2v2", "3v3"
