#!/usr/bin/env bash
# Run an RLBot match: our bot vs an opponent bot's .toml (e.g. from RLBotPack).
#   scripts/match.sh /path/to/opponent/bot.toml
# Requires the RLBot v5 Python package (pip install --user --pre rlbot),
# the RLBotServer binary in libs/rlbot/, and Rocket League on this machine.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$REPO/bot/rlbot-config"
OPP="${1:?Usage: scripts/match.sh /path/to/opponent/bot.toml}"
OPP="$(realpath "$OPP")"

[[ -f "$OPP" ]] || { echo "No such file: $OPP" >&2; exit 1; }

GEN="$CONFIG_DIR/match-vs-generated.toml"
cat > "$GEN" <<EOF
# Generated by scripts/match.sh -- do not edit; regenerate instead.
[rlbot]
launcher = "Steam"
auto_start_agents = true
wait_for_agents = true

[match]
game_mode = "Soccar"
game_map_upk = "Stadium_P"
existing_match_behavior = "Restart"
enable_state_setting = true

[[cars]]
team = "Blue"
type = "RLBot"
config_file = "bot.toml"

[[cars]]
team = "Orange"
type = "RLBot"
config_file = "$OPP"
EOF

exec python3 "$REPO/scripts/run_match.py" "$GEN"
