#include "NectoPolicy.h"

#include <RLGymCPP/CommonValues.h>

#include <torch/csrc/jit/ir/constants.h>
#include <torch/csrc/jit/ir/ir.h>
#include <torch/cuda.h>
#include <torch/script.h>

#include <algorithm>
#include <cmath>
#include <limits>
#include <map>
#include <stdexcept>

using namespace RLGC;

namespace Dash {

const char *NectoFamilyName(NectoFamily family) {
	return family == NectoFamily::Nexto ? "Nexto" : "Necto";
}

namespace {

// necto_obs.py `_norm`. Note positions are divided by 2300 as well as
// velocities -- that is Necto's convention, not a transcription slip.
constexpr float NORM[NectoPolicy::FEATURES] = {
	1, 1, 1, 1, 1,          // 0-4   type flags
	2300, 2300, 2300,       // 5-7   position
	2300, 2300, 2300,       // 8-10  linear velocity
	1, 1, 1,                // 11-13 forward
	1, 1, 1,                // 14-16 up
	5.5f, 5.5f, 5.5f,       // 17-19 angular velocity
	1, 1, 1, 1              // 20-23 boost, timer, on ground, has flip
};

// necto_obs.py `_invert`: negate x and y of every vector triple, keep z.
constexpr float INVERT[NectoPolicy::FEATURES] = {
	1,  1,  1, 1, 1, //
	-1, -1, 1,       // position
	-1, -1, 1,       // linear velocity
	-1, -1, 1,       // forward
	-1, -1, 1,       // up
	-1, -1, 1,       // angular velocity
	1,  1,  1, 1     //
};

constexpr int NUM_HEADS = 5;
constexpr int MAX_HEAD_SIZE = 3;

// Column layout, shared by both families. Named because the Nexto relative pass
// walks it by stride rather than by triple.
constexpr int COL_POS = 5;      // 5-7
constexpr int COL_LIN_VEL = 8;  // 8-10
constexpr int COL_FORWARD = 11; // 11-13
constexpr int COL_ANG_VEL = 17; // 17-19
constexpr int COL_TIMER = 21;   // demo respawn / pad cooldown, or the raw flags

// Nexto's action space, transcribed from nexto/agent.py `make_lookup_table`.
//
// This is deliberately NOT RLGC::DefaultAction's table, even though the two are
// currently generated by identical loops in identical order and agree entry for
// entry. That agreement is a fact about our action parser, which is ours to
// change -- there is already one local patch in it -- whereas this table is part
// of Nexto's trained weights and is not. Sharing them would turn a future tweak
// to our own action set into a silent corruption of the opponent.
std::vector<Action> BuildNextoLookupTable() {
	constexpr float R_B[] = {0, 1};
	constexpr float R_F[] = {-1, 0, 1};

	std::vector<Action> actions;

	// Ground
	for (float throttle : R_F)
		for (float steer : R_F)
			for (float boost : R_B)
				for (float handbrake : R_B) {
					if (boost == 1 && throttle != 1)
						continue;
					actions.push_back({throttle, steer, 0, steer, 0, 0, boost,
									   handbrake});
				}

	// Aerial
	for (float pitch : R_F)
		for (float yaw : R_F)
			for (float roll : R_F)
				for (float jump : R_B)
					for (float boost : R_B) {
						if (jump == 1 && yaw != 0) // only need roll for sideflip
							continue;
						if (pitch == 0 && roll == 0 && jump == 0) // ground dupe
							continue;
						const float handbrake =
							(jump == 1 && (pitch != 0 || yaw != 0 || roll != 0))
								? 1.f
								: 0.f;
						actions.push_back({boost, yaw, pitch, yaw, roll, jump,
										   boost, handbrake});
					}

	return actions;
}

// Reads the family off the traced forward's return type.
//
// Necto returns ((h0, h1, h2, h3, h4), (weights,)); Nexto returns
// (logits, (weights, weights)). So the first element of the returned tuple is a
// tuple for one and a bare tensor for the other -- a structural difference, not
// a guess from the filename.
NectoFamily DetectFamily(torch::jit::script::Module &mod) {
	const c10::FunctionSchema &schema =
		mod.get_method("forward").function().getSchema();
	if (schema.returns().size() != 1)
		throw std::runtime_error("forward() does not return a single value");

	const auto tuple = schema.returns()[0].type()->cast<c10::TupleType>();
	if (!tuple || tuple->elements().empty())
		throw std::runtime_error("forward() does not return a tuple");

	const c10::TypePtr &head = tuple->elements()[0];
	if (head->cast<c10::TupleType>())
		return NectoFamily::Necto;
	if (head->cast<c10::TensorType>())
		return NectoFamily::Nexto;

	throw std::runtime_error("unrecognised head type '" + head->str() + "'");
}

// Rewrites every baked-in device constant in a loaded module to `dev`.
//
// Nexto's ControlsPredictorDot embeds its action lookup table and dots it
// against the player embedding, and the trace froze the table's `.to(device)`
// as `.to(device=cpu)` because Rolv traced on CPU:
//
//     input = torch.to(CONSTANTS.c2, dtype=6, layout=0, device=torch.device("cpu"))
//     res = torch.einsum("ad,bpd->bpa", [(net).forward(input), player_emb])
//
// torch::jit::load(path, kCUDA) moves the weights but not that node, so the
// einsum gets a CPU table against CUDA weights and throws "Expected all tensors
// to be on the same device". Necto has no such node, which is why this only
// showed up on the Nexto model.
//
// Rewriting the constant is the honest fix: the alternative is running the whole
// opponent on the CPU, and this forward is serial on the collection thread with
// every arena worker parked, so that cost lands on every env step. Loading is
// lazy about building execution plans, so editing the graph here is safe.
//
// Returns how many constants were changed, so the caller can say so out loud
// rather than silently depending on a graph detail of someone else's export.
int RetargetDeviceConstants(torch::jit::Block *block, torch::Device dev) {
	int changed = 0;

	for (auto it = block->nodes().begin(); it != block->nodes().end();) {
		torch::jit::Node *node = *it;
		++it; // the node may be destroyed below

		for (torch::jit::Block *sub : node->blocks())
			changed += RetargetDeviceConstants(sub, dev);

		if (node->kind() != torch::jit::prim::Constant ||
			node->outputs().size() != 1)
			continue;

		torch::jit::Value *out = node->output();
		const auto value = torch::jit::toIValue(out);
		if (!value || !value->isDevice() || value->toDevice() == dev)
			continue;

		torch::jit::WithInsertPoint guard(node);
		torch::jit::Value *repl =
			block->owningGraph()->insertConstant(c10::IValue(dev));
		out->replaceAllUsesWith(repl);
		node->destroy();
		changed++;
	}

	return changed;
}

int RetargetDeviceConstants(torch::jit::script::Module &mod,
							torch::Device dev) {
	int changed = 0;
	for (auto sub : mod.modules())
		for (auto &method : sub.get_methods())
			changed += RetargetDeviceConstants(method.graph()->block(), dev);
	return changed;
}

} // namespace

struct NectoPolicy::Module {
	torch::jit::script::Module mod;
	torch::Device device = torch::kCPU;
};

NectoPolicy::NectoPolicy(const std::filesystem::path &modelPath, float beta,
						 int64_t seed, bool useGPU)
	: beta(std::clamp(beta, 0.f, 1.f)),
	  rng(seed < 0 ? std::random_device{}() : static_cast<uint32_t>(seed)) {
	if (!std::filesystem::is_regular_file(modelPath))
		throw std::runtime_error("NectoPolicy: no model file at " +
								 modelPath.string());

	// The device is the caller's call, and during training it should be the GPU.
	//
	// This was originally CPU-only, on the reasoning that training owns the GPU
	// and ~3ms for a batch of ~50 is nothing. That was wrong about where the
	// 3ms lands: this forward runs from preStepFn, which the learner calls
	// AFTER envSet->Sync() and BEFORE StepSecondHalf -- serial on the collection
	// thread, with all twelve arena workers parked. So it is 3ms added to every
	// env step, not 3ms hidden in the noise. Measured against the same GPU
	// sitting at ~11% utilisation for the whole collection phase.
	//
	// Note this still does NOT call at::set_num_threads(), which matters for the
	// CPU fallback below. Necto's own agent.py does, because under RLBot it must
	// not steal the game's CPU -- but that setting is process-global in libtorch,
	// so calling it here throttled PPO's own inference and update to a single
	// thread. Measured cost of getting this wrong: collection throughput roughly
	// halved.
	onGPU = useGPU && torch::cuda::is_available();

	module = std::make_unique<Module>();
	module->device = onGPU ? torch::Device(torch::kCUDA) : torch::Device(torch::kCPU);
	try {
		module->mod = torch::jit::load(modelPath.string(), module->device);
		module->mod.eval();
		family = DetectFamily(module->mod);
		// Only on the GPU, and only ever a no-op on Necto. See the function.
		if (onGPU)
			RetargetDeviceConstants(module->mod, module->device);
	} catch (const std::exception &e) {
		throw std::runtime_error("NectoPolicy: failed to load " +
								 modelPath.string() + ": " + e.what());
	}

	if (family == NectoFamily::Nexto)
		lookupTable = NextoLookupTable();

	// agent.py: logits *= log((beta + 1) / (1 - beta), 3). Falls out to exactly
	// 1.0 at beta = 0.5, which is why that value is plain on-policy sampling.
	logitScale = (this->beta >= 1.f || this->beta <= 0.f)
					 ? 0.f
					 : std::log((this->beta + 1.f) / (1.f - this->beta)) /
						   std::log(3.f);
}

NectoPolicy::~NectoPolicy() = default;

std::vector<Action> NectoPolicy::NextoLookupTable() {
	return BuildNextoLookupTable();
}

int NectoPolicy::TokenCount(const GameState &state) {
	return 1 + static_cast<int>(state.players.size()) +
		   CommonValues::BOOST_LOCATIONS_AMOUNT;
}

void NectoPolicy::BuildObs(NectoFamily family, const GameState &gs,
						   int playerIdx, const Action &prevAction, float *qOut,
						   float *kvOut) {
	const bool nexto = family == NectoFamily::Nexto;
	const int numPlayers = static_cast<int>(gs.players.size());
	const int n = TokenCount(gs);

	if (playerIdx < 0 || playerIdx >= numPlayers)
		throw std::runtime_error("NectoPolicy::BuildObs: player index out of range");
	if (static_cast<int>(gs.boostPadTimers.size()) <
		CommonValues::BOOST_LOCATIONS_AMOUNT)
		throw std::runtime_error("NectoPolicy::BuildObs: game state has no boost pad data");
	if (nexto && static_cast<int>(gs.boostPads.size()) <
					 CommonValues::BOOST_LOCATIONS_AMOUNT)
		throw std::runtime_error("NectoPolicy::BuildObs: game state has no boost pad states");

	std::fill(kvOut, kvOut + static_cast<size_t>(n) * FEATURES, 0.f);

	// Token order. Necto is (ball, cars, pads); Nexto is (cars, ball, pads).
	// Nothing in the model can tell the difference -- EARLPerceiver has no
	// positional encoding, so kv is a set -- but matching each builder exactly
	// keeps the self-test a straight elementwise diff.
	const int ballRow = nexto ? numPlayers : 0;
	const int carRow0 = nexto ? 0 : 1;
	const int padRow0 = 1 + numPlayers;

	auto row = [&](int i) { return kvOut + static_cast<size_t>(i) * FEATURES; };
	auto setVec = [](float *r, int col, const Vec &v) {
		r[col] = v.x;
		r[col + 1] = v.y;
		r[col + 2] = v.z;
	};

	{ // Ball. Leaves the forward/up columns zero, as both builders do.
		float *r = row(ballRow);
		r[3] = 1.f; // is_ball
		setVec(r, COL_POS, gs.ball.pos);
		setVec(r, COL_LIN_VEL, gs.ball.vel);
		setVec(r, COL_ANG_VEL, gs.ball.angVel);
	}

	// Cars. Team flags are ABSOLUTE here (blue -> col 1, orange -> col 2); the
	// swap for an orange main car happens below, in the Python's order. Do not
	// shortcut this by computing the flags relative to the main car -- the
	// inversion below would then apply on top of an already-relative encoding.
	for (int i = 0; i < numPlayers; i++) {
		const Player &p = gs.players[i];
		float *r = row(carRow0 + i);
		r[p.team == Team::BLUE ? 1 : 2] = 1.f;
		setVec(r, COL_POS, p.pos);
		setVec(r, COL_LIN_VEL, p.vel);
		setVec(r, COL_FORWARD, p.rotMat.forward);
		setVec(r, 14, p.rotMat.up);
		setVec(r, COL_ANG_VEL, p.angVel);
		r[20] = p.boost / 100.f; // CarState::boost is 0-100, both want 0-1
		// Necto: the sim's real respawn timer. necto_obs.py re-seeds this to 3
		// whenever it reaches 0, which is an artifact of its RLBot port -- the
		// model was trained on the real thing.
		//
		// Nexto: the raw is_demoed flag. Its builder reads encoded_player[33],
		// which is exactly that bool, and the same function ran at training
		// time, so a timer here would be the wrong scale AND the wrong quantity.
		r[COL_TIMER] = nexto ? (p.isDemoed ? 1.f : 0.f)
							 : p.demoRespawnTimer / 10.f;
		r[22] = p.isOnGround ? 1.f : 0.f;
		r[23] = p.HasFlipOrJump() ? 1.f : 0.f;
	}

	// Boost pads. Ordering within the pad block does not matter -- the model
	// attends over the token set and each pad carries its own position -- so
	// long as position, size and timer for a row all come from the same pad.
	for (int i = 0; i < CommonValues::BOOST_LOCATIONS_AMOUNT; i++) {
		const Vec &loc = CommonValues::BOOST_LOCATIONS[i];
		float *r = row(padRow0 + i);
		r[4] = 1.f; // is_boost
		setVec(r, COL_POS, loc);
		r[20] = 0.12f + 0.88f * (loc.z > 72.f ? 1.f : 0.f); // big pads sit at z=73
		// Necto reads the true remaining cooldown; Nexto's builder puts the raw
		// availability bit here instead (its own `# FIXME boost timer`). Index
		// directly either way: GameState::GetBoostPadTimers() has its `inverted`
		// flag swapped upstream.
		r[COL_TIMER] = nexto ? (gs.boostPads[i] ? 1.f : 0.f)
							 : gs.boostPadTimers[i] / 10.f;
	}

	for (int i = 0; i < n; i++) {
		float *r = row(i);
		for (int c = 0; c < FEATURES; c++)
			r[c] /= NORM[c];
	}

	const int mainRow = carRow0 + playerIdx;
	row(mainRow)[0] = 1.f; // is_main / is_self

	// Orange plays the mirrored field.
	if (gs.players[playerIdx].team == Team::ORANGE) {
		for (int i = 0; i < n; i++) {
			float *r = row(i);
			std::swap(r[1], r[2]);
			for (int c = 0; c < FEATURES; c++)
				r[c] *= INVERT[c];
		}
	}

	// q keeps ABSOLUTE position and velocity, and must be taken before kv is
	// made relative below.
	std::copy(row(mainRow), row(mainRow) + FEATURES, qOut);
	for (int k = 0; k < static_cast<int>(Action::ELEM_AMOUNT); k++)
		qOut[FEATURES + k] = prevAction[k];

	if (!nexto) {
		// Necto: kv positions AND linear velocities become relative to the main
		// car. Nothing is rotated -- the frame stays axis-aligned to the field.
		for (int i = 0; i < n; i++) {
			float *r = row(i);
			for (int c = COL_POS; c < COL_FORWARD; c++)
				r[c] -= qOut[c];
		}
		return;
	}

	// Nexto: position only, and then every x/y pair is rotated into the main
	// car's yaw frame -- `NextoObsBuilder.convert_to_relative`. Velocity is NOT
	// subtracted; the commented-out line doing that is still in the upstream
	// source directly above the one that replaced it.
	for (int i = 0; i < n; i++) {
		float *r = row(i);
		for (int c = COL_POS; c < COL_LIN_VEL; c++)
			r[c] -= qOut[c];
	}

	// theta comes from the main car's forward, already inverted for orange, and
	// is atan2(x, y) rather than the usual atan2(y, x) -- so the rotation below
	// carries the car's nose onto +y, not +x.
	const float theta = std::atan2(qOut[COL_FORWARD], qOut[COL_FORWARD + 1]);
	const float ct = std::cos(theta);
	const float st = std::sin(theta);

	// Columns 5..19 by stride 3: position, linear velocity, forward, up and
	// angular velocity all get the same yaw rotation. q itself is left alone,
	// which is what makes it the frame everything else is expressed in.
	for (int i = 0; i < n; i++) {
		float *r = row(i);
		for (int c = COL_POS; c < COL_ANG_VEL + 3; c += 3) {
			const float x = r[c];
			const float y = r[c + 1];
			r[c] = ct * x - st * y;
			r[c + 1] = st * x + ct * y;
		}
	}
}

Action NectoPolicy::SampleAction(const float *const *heads,
								 const int *headSizes) {
	int picked[NUM_HEADS] = {};

	for (int h = 0; h < NUM_HEADS; h++) {
		const int k = headSizes[h];
		const float *logits = heads[h];

		if (beta >= 1.f) { // argmax
			int best = 0;
			for (int c = 1; c < k; c++)
				if (logits[c] > logits[best])
					best = c;
			picked[h] = best;
			continue;
		}

		if (beta <= 0.f) { // uniform
			picked[h] = std::uniform_int_distribution<int>(0, k - 1)(rng);
			continue;
		}

		float scaled[MAX_HEAD_SIZE];
		float maxLogit = -std::numeric_limits<float>::infinity();
		for (int c = 0; c < k; c++) {
			scaled[c] = logits[c] * logitScale;
			maxLogit = std::max(maxLogit, scaled[c]);
		}

		float sum = 0.f;
		for (int c = 0; c < k; c++) {
			scaled[c] = std::exp(scaled[c] - maxLogit);
			sum += scaled[c];
		}

		const float u =
			std::uniform_real_distribution<float>(0.f, 1.f)(rng) * sum;
		float acc = 0.f;
		picked[h] = k - 1;
		for (int c = 0; c < k; c++) {
			acc += scaled[c];
			if (u <= acc) {
				picked[h] = c;
				break;
			}
		}
	}

	// agent.py's mapping. Heads 0 and 1 are ternary and shift to {-1, 0, 1};
	// the rest are binary. Note pitch reuses head 0 and yaw/roll split head 1
	// on the handbrake bit -- that is why Necto's action space does not line up
	// with RLGymCPP's 90-entry lookup table.
	const float throttle = static_cast<float>(picked[0] - 1);
	const float steer = static_cast<float>(picked[1] - 1);
	const float jump = static_cast<float>(picked[2]);
	const float boost = static_cast<float>(picked[3]);
	const float handbrake = static_cast<float>(picked[4]);

	Action act = {};
	act.throttle = throttle;
	act.steer = steer;
	act.pitch = throttle;
	act.yaw = steer * (1.f - handbrake);
	act.roll = steer * handbrake;
	act.jump = jump;
	act.boost = boost;
	act.handbrake = handbrake;
	return act;
}

Action NectoPolicy::SampleLookupAction(const float *logits, int count) {
	// Same temperature semantics as SampleAction, over one wide head instead of
	// five narrow ones. nexto/agent.py runs a single Categorical here, and at
	// beta = 0 zeroes the finite logits, which is a uniform draw over all of
	// them -- every entry is finite, since nothing is padded at this width.
	int picked = 0;

	if (beta >= 1.f) { // argmax
		for (int c = 1; c < count; c++)
			if (logits[c] > logits[picked])
				picked = c;
	} else if (beta <= 0.f) { // uniform
		picked = std::uniform_int_distribution<int>(0, count - 1)(rng);
	} else {
		logitBuf.resize(count);

		float maxLogit = -std::numeric_limits<float>::infinity();
		for (int c = 0; c < count; c++) {
			logitBuf[c] = logits[c] * logitScale;
			maxLogit = std::max(maxLogit, logitBuf[c]);
		}

		float sum = 0.f;
		for (int c = 0; c < count; c++) {
			logitBuf[c] = std::exp(logitBuf[c] - maxLogit);
			sum += logitBuf[c];
		}

		const float u =
			std::uniform_real_distribution<float>(0.f, 1.f)(rng) * sum;
		float acc = 0.f;
		picked = count - 1;
		for (int c = 0; c < count; c++) {
			acc += logitBuf[c];
			if (u <= acc) {
				picked = c;
				break;
			}
		}
	}

	return lookupTable[picked];
}

void NectoPolicy::InferBatch(const std::vector<NectoRequest> &requests,
							 std::vector<Action> &outActions) {
	outActions.assign(requests.size(), Action{});
	if (requests.empty())
		return;

	// Group by token count so every batch is exact. Padding ragged batches is
	// close but not exact -- the traced model's mask is not fully wired, so
	// padded rows still perturb the logits by ~0.03. At 1v1 this is one group.
	std::map<int, std::vector<int>> byTokens;
	for (int i = 0; i < static_cast<int>(requests.size()); i++)
		byTokens[TokenCount(*requests[i].state)].push_back(i);

	for (const auto &[n, idxs] : byTokens) {
		const int b = static_cast<int>(idxs.size());

		qBuf.assign(static_cast<size_t>(b) * Q_SIZE, 0.f);
		kvBuf.assign(static_cast<size_t>(b) * n * FEATURES, 0.f);
		maskBuf.assign(static_cast<size_t>(b) * n, 0.f);

		for (int j = 0; j < b; j++) {
			const NectoRequest &req = requests[idxs[j]];
			BuildObs(family, *req.state, req.playerIdx, req.prevAction,
					 qBuf.data() + static_cast<size_t>(j) * Q_SIZE,
					 kvBuf.data() + static_cast<size_t>(j) * n * FEATURES);
		}

		c10::IValue out;
		{
			torch::NoGradGuard noGrad;

			// from_blob aliases the reused buffers rather than copying, so on
			// CPU this stays allocation-free. On GPU the .to() is the copy --
			// about 200KB per step for a 1v1 batch of ~50, against the ~3ms of
			// serial CPU forward it replaces.
			auto tQ =
				torch::from_blob(qBuf.data(), {b, 1, Q_SIZE}, torch::kFloat32);
			auto tKV = torch::from_blob(kvBuf.data(), {b, n, FEATURES},
										torch::kFloat32);
			auto tMask =
				torch::from_blob(maskBuf.data(), {b, n}, torch::kFloat32);

			if (onGPU) {
				tQ = tQ.to(module->device);
				tKV = tKV.to(module->device);
				tMask = tMask.to(module->device);
			}

			std::vector<c10::IValue> tup{tQ, tKV, tMask};
			out = module->mod.forward({c10::ivalue::Tuple::create(tup)});
		}

		// Both families return (heads, attention weights).
		const auto outer = out.toTuple()->elements();
		if (outer.empty())
			throw std::runtime_error("NectoPolicy: model returned an empty tuple");

		if (family == NectoFamily::Nexto) {
			// One [batch, 90] tensor of logits over whole control sets. view()
			// rather than a shape assertion because the trace already squeezed
			// the player axis out; this survives it coming back.
			torch::Tensor logits =
				outer[0].toTensor().to(torch::kCPU).contiguous().view({b, -1});

			const int count = static_cast<int>(logits.size(1));
			if (count != static_cast<int>(lookupTable.size()))
				throw std::runtime_error(
					"NectoPolicy: model emits " + std::to_string(count) +
					" actions, lookup table has " +
					std::to_string(lookupTable.size()));

			const float *data = logits.data_ptr<float>();
			for (int j = 0; j < b; j++)
				outActions[idxs[j]] = SampleLookupAction(
					data + static_cast<size_t>(j) * count, count);
			continue;
		}

		// Necto: a tuple of five tensors shaped [batch, 1, k].
		std::vector<torch::Tensor> heads;
		if (outer[0].isTuple()) {
			for (const auto &e : outer[0].toTuple()->elements())
				heads.push_back(e.toTensor());
		} else if (outer[0].isTensorList()) {
			for (const auto &t : outer[0].toTensorList())
				heads.push_back(torch::Tensor(t));
		} else {
			throw std::runtime_error("NectoPolicy: unexpected head container '" +
									 std::string(outer[0].tagKind()) + "'");
		}

		if (static_cast<int>(heads.size()) != NUM_HEADS)
			throw std::runtime_error("NectoPolicy: expected " +
									 std::to_string(NUM_HEADS) + " heads, got " +
									 std::to_string(heads.size()));

		// SampleAction reads these through data_ptr, so they have to be host
		// memory. A no-op when the model is already on the CPU. The logits are
		// tiny -- five heads of at most 3 values per car -- so this is a handful
		// of bytes back across the bus, not a real transfer.
		for (torch::Tensor &head : heads)
			head = head.to(torch::kCPU).contiguous();

		const float *headPtrs[NUM_HEADS];
		int headSizes[NUM_HEADS];
		for (int h = 0; h < NUM_HEADS; h++) {
			headSizes[h] = static_cast<int>(heads[h].size(-1));
			if (headSizes[h] > MAX_HEAD_SIZE)
				throw std::runtime_error("NectoPolicy: head wider than expected");
		}

		for (int j = 0; j < b; j++) {
			for (int h = 0; h < NUM_HEADS; h++)
				headPtrs[h] = heads[h].data_ptr<float>() +
							  static_cast<size_t>(j) * headSizes[h];
			outActions[idxs[j]] = SampleAction(headPtrs, headSizes);
		}
	}
}

} // namespace Dash
